standalone_tags:
        [
                {id: 0, size: 0.18},
                {id: 1, size: 0.18},
                {id: 2, size: 0.18},
                {id: 3, size: 0.18}
        ]
               
tag_bundles: []
